export const FETCH_CHARACTERS_LIST_PENDING = "FETCH_CHARACTERS_LIST_PENDING";
export const FETCH_CHARACTERS_LIST_SUCCESS = "FETCH_CHARACTERS_LIST_SUCCESS";

export const SET_CHARACTER_DATA = "SET_CHARACTER_DATA";