// Characters
export const FETCH_CHARACTERS_LIST_PENDING = "FETCH_CHARACTERS_LIST_PENDING";
export const FETCH_CHARACTERS_LIST_SUCCESS = "FETCH_CHARACTERS_LIST_SUCCESS";
export const SET_CHARACTER_DATA = "SET_CHARACTER_DATA";

// films
export const FETCH_FILMS_LIST_PENDING = "FETCH_FILMS_LIST_PENDING";
export const FETCH_FILMS_LIST_SUCCESS = "FETCH_FILMS_LIST_SUCCESS";

// vehicles
export const FETCH_VEHICLES_LIST_PENDING = "FETCH_VEHICLES_LIST_PENDING";
export const FETCH_VEHICLES_LIST_SUCCESS = "FETCH_VEHICLES_LIST_SUCCESS";

// Modals
export const TOGGLE_FILMS_MODAL = "TOGGLE_FILMS_MODAL";
export const TOGGLE_VEHICLES_MODAL = "TOGGLE_VEHICLES_MODAL";